### ISSUE TITLE
Silent permission seems to always be applied to commands

### ISSUE THREAD

**Issue by Folas1337** [FeuSalamander/Vmessage#15]
I have just updated to 1.6.0 and the commands I have set up are no longer fired when someone joins or leaves the velocity proxy.

I have immediately downgraded to 1.5.6 again and it's now working again. Could you look into this and ideally release a bug fix?

That'd be greatly appreciated! :)

**Comment by Folas1337** [comment]
Found a typo in the original, still hoping a fix for this at some point? :)

**Comment by Folas1337** [comment]
Oh, it seems that the problem is NOT the permission but this error I'm getting on Velocity:
```
[22:22:04 INFO]: [server connection] Folas1337 -> lobby1 has disconnected
[22:22:04 ERROR]: Couldn't pass DisconnectEvent to vmessage
java.lang.NullPointerException: Cannot invoke "com.moandjiezana.toml.Toml.contains(String)" because the return value of "me.feusalamander.vmessage.Configuration.getAliases()" is null
        at me.feusalamander.vmessage.Listeners.onLeave(Listeners.java:69) ~[?:?]
        at me.feusalamander.vmessage.Lmbda$75.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-296.jar:3.2.0-SNAPSHOT (git-07a525be-b296)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.2.0-SNAPSHOT-296.jar:3.2.0-SNAPSHOT (git-07a525be-b296)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.2.0-SNAPSHOT-296.jar:3.2.0-SNAPSHOT (git-07a525be-b296)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[22:22:04 INFO]: [LP] VB > folas1337 - vmessage.silent.leave - false
[22:22:15 INFO]: [connected player] Folas1337 (/<redacted>) has connected
[22:22:15 INFO]: [server connection] Folas1337 -> lobby1 has connected
[22:22:15 ERROR]: Couldn't pass ServerPostConnectEvent to vmessage
java.lang.NullPointerException: Cannot invoke "com.moandjiezana.toml.Toml.contains(String)" because the return value of "me.feusalamander.vmessage.Configuration.getAliases()" is null
        at me.feusalamander.vmessage.Listeners.onChange(Listeners.java:183) ~[?:?]
        at me.feusalamander.vmessage.Lmbda$77.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-296.jar:3.2.0-SNAPSHOT (git-07a525be-b296)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.2.0-SNAPSHOT-296.jar:3.2.0-SNAPSHOT (git-07a525be-b296)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.2.0-SNAPSHOT-296.jar:3.2.0-SNAPSHOT (git-07a525be-b296)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
```

**Comment by Folas1337** [comment]
Maybe I should read the errors and correct my config.toml, not sure how I missed that.
I gotta fix that tomorrow as I gotta go now, if I can fix it by simply adding the Alias section to the config, I'll close this afterwards.

Although it'd be ideal if this was done by default by the plugin and wouldn't need me to fix it :P
