### ISSUE TITLE
Vmessage/VelocityDiscord integration

### ISSUE THREAD

**Issue by Kriptiq** [FeuSalamander/Vmessage#20]
Velocity 3.3.0-SNAPSHOT (git-38558783-b345)
Vmessage 1.6.2
VelocityDiscord 1.8.2

Hi, I seem to have an issue with this integration. We have used Vmessage for awhile and recently seen the Discord option and have tried to add. Both plugins work fine and as intended if only one is active. If both are active we get these messages. I've gone through the configs and don't know if I'm missing something that would fix? Or if it is a different issue.

Minecraft cross-server
![example1](https://github.com/FeuSalamander/Vmessage/assets/81416196/f6ed5d01-f0d7-4dd9-bf71-0e77a8249567)

Minecraft to Discord
![example2](https://github.com/FeuSalamander/Vmessage/assets/81416196/2596e123-55cc-4110-a4fc-68be1a0b254f)

Discord to Minecraft works fine.

**Comment by Kriptiq** [comment]
I'm assuming in the Minecraft to Discord, it's the Discord plugin reading vmessage forwarding on the other 3 servers and sending to discord giving the 3 extra placeholder messages in Discord.

**Comment by Kriptiq** [comment]
I've updated to Velocity Discord 1.9.0 which seems to have fixed the discord messaging. Still have the in game messaging issue with these errors in console. I've also submitted the issue with them to see if it's on their end.

29.08 03:22:00 [Server] INFO Kriptiq -> lobby has connected
29.08 03:22:01 [Server] INFO [, 7, 4 Kriptiq , ejoined , 7Lobby]
29.08 03:22:01 [Server] INFO Kriptiq joined Lobby
29.08 03:22:01 [Server] ERROR Couldn't pass ServerPostConnectEvent to vmessage 1.6.2
29.08 03:22:01 [Server] INFO java.lang.IllegalAccessError: class me.feusalamander.vmessage.Listeners tried to access private method 'void ooo.foooooooooooo.velocitydiscord.discord.Discord.sendMessage(java.lang.String)' (me.feusalamander.vmessage.Listeners is in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @2b214b94; ooo.foooooooooooo.velocitydiscord.discord.Discord is in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @319854f0)
29.08 03:22:01 [Server] INFO at me.feusalamander.vmessage.Listeners.onChange(Listeners.java:280) ~[?:?]
29.08 03:22:01 [Server] INFO at me.feusalamander.vmessage.Lmbda$74.execute(Unknown Source) ~[?:?]
29.08 03:22:01 [Server] INFO at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[custom-java21.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
29.08 03:22:01 [Server] INFO at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[custom-java21.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
29.08 03:22:01 [Server] INFO at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[custom-java21.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
29.08 03:22:01 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
29.08 03:22:01 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
29.08 03:22:01 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
29.08 03:22:10 [Server] INFO This command does not exist.
29.08 03:22:19 [Server] INFO Kriptiq -> create has connected
29.08 03:22:19 [Server] INFO Kriptiq -> lobby has disconnected
29.08 03:22:19 [Server] INFO [, 7, 4 Kriptiq , eleft , clobby , eto join , aCreate]
29.08 03:22:19 [Server] INFO Kriptiq left lobby to join Create
29.08 03:22:19 [Server] ERROR Couldn't pass ServerPostConnectEvent to vmessage 1.6.2
29.08 03:22:19 [Server] INFO java.lang.IllegalAccessError: class me.feusalamander.vmessage.Listeners tried to access private method 'void ooo.foooooooooooo.velocitydiscord.discord.Discord.sendMessage(java.lang.String)' (me.feusalamander.vmessage.Listeners is in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @2b214b94; ooo.foooooooooooo.velocitydiscord.discord.Discord is in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @319854f0)
29.08 03:22:19 [Server] INFO at me.feusalamander.vmessage.Listeners.onChange(Listeners.java:231) ~[?:?]
29.08 03:22:19 [Server] INFO at me.feusalamander.vmessage.Lmbda$74.execute(Unknown Source) ~[?:?]
29.08 03:22:19 [Server] INFO at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[custom-java21.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
29.08 03:22:19 [Server] INFO at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[custom-java21.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
29.08 03:22:19 [Server] INFO at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[custom-java21.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
29.08 03:22:19 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
29.08 03:22:19 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
29.08 03:22:19 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
29.08 03:22:56 [Server] INFO This command does not exist.
29.08 03:23:42 [Server] INFO This command does not exist.
29.08 03:24:28 [Server] INFO This command does not exist.
29.08 03:25:14 [Server] INFO This command does not exist.
29.08 03:25:36 [Server] INFO [, a(Create) , 4 Kriptiq , 8, l> , r#message#]
29.08 03:25:36 [Server] ERROR Couldn't pass PlayerChatEvent to vmessage 1.6.2
29.08 03:25:36 [Server] INFO java.lang.IllegalAccessError: class me.feusalamander.vmessage.Listeners tried to access private method 'void ooo.foooooooooooo.velocitydiscord.discord.Discord.sendMessage(java.lang.String)' (me.feusalamander.vmessage.Listeners is in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @2b214b94; ooo.foooooooooooo.velocitydiscord.discord.Discord is in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @319854f0)
29.08 03:25:36 [Server] INFO at me.feusalamander.vmessage.Listeners.lambda$message$0(Listeners.java:359) ~[?:?]
29.08 03:25:36 [Server] INFO at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[custom-java21.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
29.08 03:25:36 [Server] INFO at me.feusalamander.vmessage.Listeners.message(Listeners.java:356) ~[?:?]
29.08 03:25:36 [Server] INFO at me.feusalamander.vmessage.Listeners.onMessage(Listeners.java:50) ~[?:?]
29.08 03:25:36 [Server] INFO at me.feusalamander.vmessage.Lmbda$73.execute(Unknown Source) ~[?:?]
29.08 03:25:36 [Server] INFO at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[custom-java21.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
29.08 03:25:36 [Server] INFO at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[custom-java21.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
29.08 03:25:36 [Server] INFO at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[custom-java21.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
29.08 03:25:36 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
29.08 03:25:36 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
29.08 03:25:36 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
